# Generated by Django 5.2.1 on 2025-05-31 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GymApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='duration_days',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
