# Generated by Django 5.2.2 on 2025-06-20 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GymApp', '0005_trainer'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='experience',
            field=models.PositiveIntegerField(default=0, verbose_name='Стаж (лет)'),
        ),
    ]
