# Generated by Django 5.2.2 on 2025-06-20 18:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GymApp', '0006_trainer_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='age_limit',
            field=models.PositiveIntegerField(default=0, verbose_name='Возрастное ограничение'),
        ),
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата проведения'),
        ),
    ]
