# Generated by Django 5.2.2 on 2025-06-22 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GymApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
