trigger:
  branches:
    include:
      - develop

stages:
  - stage: BuildAndTestAndDeploy
    displayName: "Сборка, тесты и деплой"
    jobs:
      - job: OnLocalServer
        displayName: "Self-hosted агент"
        pool:
          name: Default  

        steps:
          - script: |
              echo "Установка зависимостей для backend"
              cd gym-app/backend
              python -m pip install -r requirements.txt
              echo "Запуск тестов"
              python -m pytest
            displayName: "Run backend tests (pytest)"

          - script: |
              echo "Перезапуск контейнеров"
              cd gym-app
              docker-compose down
              docker-compose up -d --build
            displayName: "Build & Deploy (docker-compose)"

