trigger:
  branches:
    include:
      - develop

stages:
  - stage: TestAndDeploy
    displayName: "Тесты и деплой"
    jobs:
      - job: DockerizedTests
        displayName: "Запуск pytest в контейнере"
        pool:
          name: Default

        steps:
          - script: |
              echo "Запуск тестов в Docker"
              cd gym-app
              docker-compose -f docker-compose.test.yml up --abort-on-container-exit --build
            displayName: "Run pytest inside container"

          - script: |
              echo "Деплой приложения"
              cd gym-app
              docker-compose down
              docker-compose up -d --build
            displayName: "Deploy containers"
