# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - develop

stages:
  - stage: BuildAndDeploy
    jobs:
      - job: BuildOnMyServer
        pool:
          name: Default  # Имя твоего self-hosted pool
        steps:
          - script: |
              cd gym-app
              docker-compose down
              docker-compose up -d --build
            displayName: "Build and deploy on local server"
