version: '3.9'

services:
  backend-tests:
    container_name: omezhka-backend-tests
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    working_dir: /app
    entrypoint: ""
    command: >
      sh -c "pip install -r requirements.txt &&
             pytest GymApp/tests --cov=GymApp --cov-report=xml"
    environment:
      - SECRET_KEY=${SECRET_KEY}


